### PR TITLE
ci: Add isort to linting workflow

### LINKED ISSUE #53: Add isort to linting in CI
I didn't see where this [isort] hooks into CI, how do we test to make sure this sorting is respected?

_Originally posted by @dguest in https://github.com/dguest/pandamonium/issues/51#issuecomment-764464344_

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #53 

Add `isort` to the linting workflow in CI and add `isort` to the `lint` extra.

**Suggested squash and merge commit message:**

```
* Add isort to 'lint' extra
* Add isort to linting GHA workflow
* Add pre-commit.ci status badge to README
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@dguest I'd encourage enabling [`pre-commit.ci`](https://pre-commit.ci/) as well, which is great because it not only runs and enforces the `pre-commit` hooks in `.pre-commit-config.yaml` but if it finds those failed it will try to push back fixes to the PR and it will also periodically check for new releases to the hook libraries and open up automatic PRs to update them for you.

**Comment by dguest** [comment]
Sounds fancy. No objections here.

**Comment by matthewfeickert** [comment]
> Sounds fancy. No objections here.

@dguest cool. :+1: I can't enable [`pre-commit.ci`](https://pre-commit.ci/) as this project is under your name, so I don't have settings control. Can you enable it?

**Comment by dguest** [comment]
I pushed a few buttons, I think it's enabled now.

**Comment by matthewfeickert** [comment]
> I pushed a few buttons, I think it's enabled now.

Hm, seems not quite yet @dguest as

[pre-commit.ci status](https://results.pre-commit.ci/latest/github/dguest/pandamonium/master)

is still showing no run.

**Pull request merged**
